apiVersion: v1
kind: Service
metadata:
  name: pos-backend-web
  labels:
    app: pos-backend-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: pos-backend-web
  sessionAffinity: None

